import { studentTotalCount } from "./students";

export const summaryStats = [
  {
    label: "전체 학생 수",
    value: `${studentTotalCount}명`,
    note: "현재 학생 관리 리스트와 같은 기준으로 집계됩니다.",
    tone: "rose" as const,
    emoji: "👥",
    badge: "동기화됨",
    href: "/dashboard/students",
  },
  {
    label: "오늘 수업 수",
    value: "6개",
    note: "오전 2개, 오후 4개로 균형 있게 배치되어 있습니다.",
    tone: "gold" as const,
    emoji: "📅",
    badge: "오늘 일정",
  },
  {
    label: "미완료 과제 수",
    value: "14개",
    note: "오늘 마감 기준 과제가 먼저 정리되어야 합니다.",
    tone: "peach" as const,
    emoji: "📌",
    badge: "확인 필요",
  },
  {
    label: "시험 임박 학생 수",
    value: "9명",
    note: "3일 이내 시험 학생이 먼저 점검 대상입니다.",
    tone: "soft" as const,
    emoji: "⏳",
    badge: "D-14",
  },
];

export const dashboardHero = {
  title: "김민정 선생님, 안녕하세요! 👋",
  subtitle: "오늘도 학생들의 흐름을 한눈에 정리해두면 수업 준비가 훨씬 가벼워집니다.",
};

export const aiInsights = {
  classInsights: [
    {
      label: "반별 인사이트",
      school: "서울고등학교",
      className: "수학 A반",
      metricLabel: "평균 성취도",
      metricValue: "84%",
      delta: "+6%",
      note: "이번 주는 함수 단원에서 점수가 가장 빠르게 올라가고 있습니다.",
      chartBars: [44, 52, 58, 61, 67, 73, 84],
      focusLabel: "취약 지점",
      focusValue: "미분 응용",
    },
    {
      label: "반별 인사이트",
      school: "서울고등학교",
      className: "영어 B반",
      metricLabel: "평균 성취도",
      metricValue: "79%",
      delta: "+3%",
      note: "독해 속도는 좋아졌지만 어휘 누적 복습이 조금 더 필요합니다.",
      chartBars: [41, 45, 53, 58, 62, 71, 79],
      focusLabel: "취약 지점",
      focusValue: "어휘 복습",
    },
    {
      label: "반별 인사이트",
      school: "강남고등학교",
      className: "수학 B반",
      metricLabel: "평균 성취도",
      metricValue: "71%",
      delta: "+2%",
      note: "문제 풀이 속도는 안정적이지만 개념 설명을 다시 정리할 필요가 있습니다.",
      chartBars: [38, 42, 47, 52, 58, 64, 71],
      focusLabel: "취약 지점",
      focusValue: "서술형 풀이",
    },
    {
      label: "반별 인사이트",
      school: "강남고등학교",
      className: "국어 A반",
      metricLabel: "평균 성취도",
      metricValue: "68%",
      delta: "-1%",
      note: "지문 해석은 좋지만 표현 문제에서 점수가 들쭉날쭉합니다.",
      chartBars: [35, 39, 44, 46, 53, 60, 68],
      focusLabel: "취약 지점",
      focusValue: "표현력",
    },
    {
      label: "반별 인사이트",
      school: "서초고등학교",
      className: "수학 C반",
      metricLabel: "평균 성취도",
      metricValue: "76%",
      delta: "+4%",
      note: "중단원 문제에서 정답률이 꾸준히 오르고 있습니다.",
      chartBars: [40, 46, 52, 56, 62, 69, 76],
      focusLabel: "취약 지점",
      focusValue: "복합 응용",
    },
    {
      label: "반별 인사이트",
      school: "서초고등학교",
      className: "영어 A반",
      metricLabel: "평균 성취도",
      metricValue: "82%",
      delta: "+5%",
      note: "문장 해석은 안정적이고, 이번 주는 작문 점검이 핵심입니다.",
      chartBars: [45, 50, 57, 63, 69, 75, 82],
      focusLabel: "취약 지점",
      focusValue: "영작 구성",
    },
    {
      label: "반별 인사이트",
      school: "한빛고등학교",
      className: "과학 A반",
      metricLabel: "평균 성취도",
      metricValue: "61%",
      delta: "+8%",
      note: "기본 개념 이해는 빠르게 잡히고 있고, 실험 보고서 정리가 남아 있습니다.",
      chartBars: [29, 34, 40, 45, 51, 56, 61],
      focusLabel: "취약 지점",
      focusValue: "실험 서술",
    },
    {
      label: "반별 인사이트",
      school: "한빛고등학교",
      className: "수학 B반",
      metricLabel: "평균 성취도",
      metricValue: "58%",
      delta: "+1%",
      note: "기초 유형은 따라오고 있으나 응용 문제는 속도를 더 올릴 필요가 있습니다.",
      chartBars: [26, 31, 36, 41, 46, 52, 58],
      focusLabel: "취약 지점",
      focusValue: "응용 문제",
    },
    {
      label: "반별 인사이트",
      school: "청운고등학교",
      className: "수학 A반",
      metricLabel: "평균 성취도",
      metricValue: "91%",
      delta: "+7%",
      note: "기본기와 응용 모두 안정적이며 상위권 유지 흐름이 좋습니다.",
      chartBars: [54, 59, 64, 70, 76, 83, 91],
      focusLabel: "취약 지점",
      focusValue: "심화 문제",
    },
    {
      label: "반별 인사이트",
      school: "청운고등학교",
      className: "영어 C반",
      metricLabel: "평균 성취도",
      metricValue: "87%",
      delta: "+4%",
      note: "독해 정확도가 높고, 지금은 시간 배분을 더 매끈하게 정리하는 단계입니다.",
      chartBars: [48, 54, 59, 65, 72, 79, 87],
      focusLabel: "취약 지점",
      focusValue: "시간 배분",
    },
    {
      label: "반별 인사이트",
      school: "수서고등학교",
      className: "국어 B반",
      metricLabel: "평균 성취도",
      metricValue: "63%",
      delta: "+2%",
      note: "기본 독해는 안정적이지만 서술형 채점 기준을 다시 맞춰야 합니다.",
      chartBars: [32, 36, 41, 46, 51, 57, 63],
      focusLabel: "취약 지점",
      focusValue: "서술형",
    },
    {
      label: "반별 인사이트",
      school: "수서고등학교",
      className: "영어 A반",
      metricLabel: "평균 성취도",
      metricValue: "67%",
      delta: "-2%",
      note: "단어량은 유지되고 있으나 독해 문장 연결이 조금 흔들립니다.",
      chartBars: [34, 37, 42, 47, 53, 59, 67],
      focusLabel: "취약 지점",
      focusValue: "문장 연결",
    },
  ],
  studentInsight: {
    label: "학생 인사이트",
    title: "눈에 띄는 학생",
    subtitle: "상승 흐름과 관리 포인트가 보이는 학생을 먼저 확인합니다.",
    students: [
      {
        name: "김민주",
        className: "수학 A반",
        badge: "상승",
        note: "최근 2주 성취도가 빠르게 상승했습니다.",
      },
      {
        name: "박하린",
        className: "영어 B반",
        badge: "주의",
        note: "독해는 안정적이지만 어휘 복습이 필요합니다.",
      },
      {
        name: "이서준",
        className: "수학 A반",
        badge: "확인",
        note: "오답 재발이 줄었고 시험 전 마무리만 남았습니다.",
      },
    ],
  },
};

export const examAlert = {
  label: "EXAM ALERT",
  title: "기말고사 D-14",
  subtitle: "시험 대비 학습 진척도",
  progress: 82,
};

export const examSchools = [
  {
    name: "서울고등학교",
    examName: "기말고사",
    examDate: "4월 12일",
    daysLeft: 14,
    overallProgress: 82,
    classes: [
      { name: "1반", progress: 82 },
      { name: "2반", progress: 76 },
      { name: "3반", progress: 69 },
    ],
  },
  {
    name: "강남고등학교",
    examName: "중간고사",
    examDate: "4월 9일",
    daysLeft: 11,
    overallProgress: 74,
    classes: [
      { name: "1반", progress: 88 },
      { name: "2반", progress: 71 },
      { name: "4반", progress: 64 },
    ],
  },
  {
    name: "서초고등학교",
    examName: "기말고사",
    examDate: "4월 15일",
    daysLeft: 17,
    overallProgress: 69,
    classes: [
      { name: "1반", progress: 79 },
      { name: "2반", progress: 73 },
      { name: "3반", progress: 61 },
    ],
  },
  {
    name: "한빛고등학교",
    examName: "모의평가",
    examDate: "4월 18일",
    daysLeft: 20,
    overallProgress: 58,
    classes: [
      { name: "1반", progress: 84 },
      { name: "2반", progress: 67 },
      { name: "5반", progress: 58 },
    ],
  },
  {
    name: "청운고등학교",
    examName: "기말고사",
    examDate: "4월 22일",
    daysLeft: 24,
    overallProgress: 91,
    classes: [
      { name: "1반", progress: 90 },
      { name: "2반", progress: 77 },
      { name: "3반", progress: 70 },
    ],
  },
  {
    name: "수서고등학교",
    examName: "중간고사",
    examDate: "4월 7일",
    daysLeft: 9,
    overallProgress: 63,
    classes: [
      { name: "1반", progress: 80 },
      { name: "2반", progress: 74 },
      { name: "3반", progress: 63 },
    ],
  },
];

export const todaySchedule = [
  {
    time: "09:00",
    duration: "60분",
    title: "고3 수학 1:1 수업",
    student: "이서준 · 개념 복습과 오답 정리",
    memo: "미분 단원 핵심 문제를 다시 풀어보고, 전주 숙제에서 틀린 유형을 빠르게 점검합니다.",
    status: "수업 입장",
    tone: "rose" as const,
  },
  {
    time: "15:30",
    duration: "90분",
    title: "고2 영어 수업",
    student: "박지민 학생",
    memo: "중간고사 대비 문법과 독해 포인트를 집중 정리합니다.",
    status: "수업 입장",
    tone: "peach" as const,
  },
];

export const recentActivity = [
  {
    time: "방금 전",
    student: "강한 학생",
    action: "과제 제출 완료",
    detail: "영어 단어 테스트 1차 과제가 정상 제출되었습니다.",
  },
  {
    time: "12분 전",
    student: "김지수 학부모",
    action: "메시지 도착",
    detail: "학부모님으로부터 확인 메시지가 도착했습니다.",
  },
  {
    time: "1시간 전",
    student: "최우식 학생",
    action: "출석률 경고",
    detail: "학생의 출석률이 낮아 점검이 필요합니다.",
  },
];

export const quickActions = [
  {
    label: "학생 추가",
    description: "새 학생 기본 정보를 빠르게 등록합니다.",
    tone: "rose" as const,
    icon: "👤",
  },
  {
    label: "과제 등록",
    description: "수업 후 바로 숙제와 마감일을 연결합니다.",
    tone: "gold" as const,
    icon: "🗂️",
  },
  {
    label: "수업 일정",
    description: "오늘의 수업 흐름을 한눈에 정리합니다.",
    tone: "peach" as const,
    icon: "🕒",
  },
  {
    label: "리포트 확인",
    description: "핵심 지표와 변화 흐름을 바로 봅니다.",
    tone: "soft" as const,
    icon: "📊",
  },
];

export const examHighlights = [
  {
    name: "이서준",
    subject: "수학",
    examDate: "4월 12일",
    daysLeft: 19,
    status: "복습 필요",
    note: "미분 단원 기초 문제를 다시 잡아야 합니다.",
  },
  {
    name: "박하린",
    subject: "영어",
    examDate: "4월 9일",
    daysLeft: 16,
    status: "집중 관리",
    note: "독해 속도와 어휘 정리가 우선입니다.",
  },
];
