export type StudentRecord = {
  id: string;
  name: string;
  school: string;
  grade: string;
  className: string;
  subject: string;
  recentProgress: string;
  recentTag: string;
  score: number;
  examDays: number;
  overdueAssignments: number;
  assignmentDone: number;
  assignmentTotal: number;
  weakTopic: string;
  status: "상승" | "주의" | "시험 임박" | "안정";
  note: string;
};

export const students: StudentRecord[] = [
  {
    id: "AIM_24001",
    name: "김민주",
    school: "서울고등학교",
    grade: "고3",
    className: "수학 A반",
    subject: "수학",
    recentProgress: "미적분 II",
    recentTag: "Ch.04",
    score: 84,
    examDays: 14,
    overdueAssignments: 0,
    assignmentDone: 17,
    assignmentTotal: 20,
    weakTopic: "미분 응용",
    status: "상승",
    note: "최근 2주 동안 함수와 미분 단원 성취도가 빠르게 상승했습니다.",
  },
  {
    id: "AIM_24005",
    name: "이서준",
    school: "서울고등학교",
    grade: "고3",
    className: "수학 A반",
    subject: "수학",
    recentProgress: "수학(상)",
    recentTag: "Ch.12",
    score: 78,
    examDays: 5,
    overdueAssignments: 1,
    assignmentDone: 8,
    assignmentTotal: 25,
    weakTopic: "서술형 풀이",
    status: "시험 임박",
    note: "기본 문제는 안정적이지만 시험 전 서술형 마무리가 필요합니다.",
  },
  {
    id: "AIM_24012",
    name: "박하린",
    school: "서울고등학교",
    grade: "고2",
    className: "영어 B반",
    subject: "영어",
    recentProgress: "Reading V",
    recentTag: "Ch.12",
    score: 71,
    examDays: 11,
    overdueAssignments: 2,
    assignmentDone: 12,
    assignmentTotal: 20,
    weakTopic: "어휘 복습",
    status: "주의",
    note: "독해는 유지되고 있으나 어휘 복습량이 부족합니다.",
  },
  {
    id: "AIM_24021",
    name: "최지은",
    school: "서울고등학교",
    grade: "고1",
    className: "국어 A반",
    subject: "국어",
    recentProgress: "문학의 이해",
    recentTag: "Ch.01",
    score: 88,
    examDays: 22,
    overdueAssignments: 0,
    assignmentDone: 30,
    assignmentTotal: 30,
    weakTopic: "서술형",
    status: "안정",
    note: "지문 해석과 요약 정리가 안정적으로 유지되고 있습니다.",
  },
  {
    id: "AIM_24028",
    name: "한도윤",
    school: "강남고등학교",
    grade: "고3",
    className: "수학 B반",
    subject: "수학",
    recentProgress: "미적분 응용",
    recentTag: "Ch.08",
    score: 76,
    examDays: 11,
    overdueAssignments: 1,
    assignmentDone: 14,
    assignmentTotal: 20,
    weakTopic: "복합 응용",
    status: "상승",
    note: "문제 풀이 속도는 좋아졌고, 응용 유형에서 상승세가 보입니다.",
  },
  {
    id: "AIM_24031",
    name: "정서윤",
    school: "강남고등학교",
    grade: "고2",
    className: "국어 A반",
    subject: "국어",
    recentProgress: "독서 분석",
    recentTag: "Ch.03",
    score: 68,
    examDays: 11,
    overdueAssignments: 3,
    assignmentDone: 8,
    assignmentTotal: 22,
    weakTopic: "표현력",
    status: "주의",
    note: "지문 이해는 괜찮지만 서술형 문장 구성에서 흔들림이 있습니다.",
  },
  {
    id: "AIM_24036",
    name: "오지후",
    school: "서초고등학교",
    grade: "고3",
    className: "수학 C반",
    subject: "수학",
    recentProgress: "확률과 통계",
    recentTag: "Ch.06",
    score: 82,
    examDays: 17,
    overdueAssignments: 0,
    assignmentDone: 20,
    assignmentTotal: 20,
    weakTopic: "복합 응용",
    status: "안정",
    note: "중단원 문제 정답률이 높고 유지 흐름이 좋습니다.",
  },
  {
    id: "AIM_24042",
    name: "윤하린",
    school: "서초고등학교",
    grade: "고1",
    className: "영어 A반",
    subject: "영어",
    recentProgress: "Grammar Step",
    recentTag: "Ch.05",
    score: 74,
    examDays: 17,
    overdueAssignments: 1,
    assignmentDone: 15,
    assignmentTotal: 20,
    weakTopic: "영작 구성",
    status: "상승",
    note: "문장 해석은 안정적이며 작문 점검 단계로 넘어가고 있습니다.",
  },
  {
    id: "AIM_24048",
    name: "문수현",
    school: "한빛고등학교",
    grade: "고2",
    className: "과학 A반",
    subject: "과학",
    recentProgress: "물리 개념",
    recentTag: "Ch.07",
    score: 61,
    examDays: 20,
    overdueAssignments: 2,
    assignmentDone: 11,
    assignmentTotal: 24,
    weakTopic: "실험 서술",
    status: "주의",
    note: "기본 개념은 잡히고 있고, 실험 보고서 정리가 더 필요합니다.",
  },
  {
    id: "AIM_24051",
    name: "장예빈",
    school: "청운고등학교",
    grade: "고3",
    className: "영어 C반",
    subject: "영어",
    recentProgress: "Reading Speed",
    recentTag: "Ch.09",
    score: 87,
    examDays: 24,
    overdueAssignments: 0,
    assignmentDone: 18,
    assignmentTotal: 18,
    weakTopic: "시간 배분",
    status: "상승",
    note: "독해 정확도가 높고, 시간 배분만 더 매끈하게 맞추면 됩니다.",
  },
  {
    id: "AIM_24057",
    name: "서지안",
    school: "수서고등학교",
    grade: "고2",
    className: "국어 B반",
    subject: "국어",
    recentProgress: "서술형 정리",
    recentTag: "Ch.02",
    score: 63,
    examDays: 9,
    overdueAssignments: 2,
    assignmentDone: 9,
    assignmentTotal: 18,
    weakTopic: "서술형",
    status: "시험 임박",
    note: "기본 독해는 안정적이지만 서술형 채점 기준을 다시 맞춰야 합니다.",
  },
  {
    id: "AIM_24063",
    name: "김태윤",
    school: "수서고등학교",
    grade: "고1",
    className: "영어 A반",
    subject: "영어",
    recentProgress: "Sentence Link",
    recentTag: "Ch.04",
    score: 67,
    examDays: 9,
    overdueAssignments: 1,
    assignmentDone: 10,
    assignmentTotal: 16,
    weakTopic: "문장 연결",
    status: "주의",
    note: "단어량은 유지되고 있으나 독해 문장 연결이 조금 흔들립니다.",
  },
];

export const studentTotalCount = students.length;
